### ISSUE TITLE
Put dotfiles paths all on separate lines?

### ISSUE THREAD

**Issue by anishathalye** [Aviator45003/init-dotfiles#1]
If you split up the stuff in https://github.com/Aviator45003/easy-dotfiles/blob/04fe42ed52e27a5c17c53d068325f21f3eae6144/easy_setup.sh#L85 onto separate lines, you'll get better diffs.

**Comment by Vaelatern** [comment]
That would mean changing the way the array is declared, unless I can find a workaround.

**Comment by Vaelatern** [comment]
False. Can just spread out to newlines.
