### ISSUE TITLE
Quick install not working

### ISSUE THREAD

**Issue by dijonkitchen** [Aviator45003/init-dotfiles#12]
I'm following the "Get Running in 5 minutes" section in the readme. 

I can download the install file fine on the first line:
curl -fsSLO https://raw.githubusercontent.com/Vaelatern/init-dotfiles/master/init_dotfiles.sh

But when I run ./init_dotfiles.sh I get an error:
zsh: permission denied: ./init_dotfiles.sh

**Comment by Vaelatern** [comment]
To fix this, you want to `chmod +x ./init_dotfiles.sh`. I'll investigate why this isn't working.

**Comment by MathieuDebit** [comment]
Still a problem (but `chmod` do the trick). Did you took a look at it? Thanks 🙏

**Comment by anishathalye** [comment]
It's because `curl` won't make the downloaded file executable. @Vaelatern perhaps consider adding a `chmod +x ./init_dotfiles.sh` in between, or just change to `curl -fsSL https://raw.githubusercontent.com/Vaelatern/init-dotfiles/master/init_dotfiles.sh | bash`
