### ISSUE TITLE
Use default git commit name/email if not set already?

### ISSUE THREAD

**Issue by anishathalye** [Aviator45003/init-dotfiles#2]
If a user doesn't have `user.name` or `user.email` set in their gitconfig, then the `git commit -m "Initial commit"` step will fail.

Is this the right way to handle that scenario? Or is it better to prompt the user? Or is it better just to use some default name/email like `easy-dotfiles <aviator45003/easy-dotfiles>`.

**Comment by Vaelatern** [comment]
This is part of why the install process is done first. We are, however, currently making the assumption that their `.gitconfig` is set up prior to this. There is no flag specifically checking the `.gitconfig` being correct, but if they choose to not install their dotfiles, the commit won't be made (the installerrun flag goes to 0).

I would be up to helping the user set up their name and email if it is not set.

**Comment by anishathalye** [comment]
That sounds like a good idea. Just `read`ing the things in and passing them to `git config --global user.{name,email}` seems reasonable.

**Comment by Vaelatern** [comment]
And I can test because `git config` returns a 1 if it fails to find a value.

**Comment by anishathalye** [comment]
You can also test the return value of `git config --get user.{name,email}`.

**Comment by Vaelatern** [comment]
Addressed, testing the code before committing.
