### ISSUE TITLE
Pretty print dotbot setup actions

### ISSUE THREAD

**Issue by joshblum** [Aviator45003/init-dotfiles#3]
![screen shot 2015-06-10 at 7 19 43 pm](https://cloud.githubusercontent.com/assets/1144020/8087805/be3e5c74-0fa5-11e5-9f39-b41e46bbd0ce.png)
Would be a lot easy to read if newline separated, especially the content of the `install.conf.yaml` file

**Comment by Vaelatern** [comment]
One line in the code where that is decided, [line 45](https://github.com/Aviator45003/easy-dotfiles/blob/master/easy_setup.sh#L45).

If you can get that to work, that's great! I had a stab at it, but it wasn't so nice.

**Comment by joshblum** [comment]
Perfect I'll take a look :)

**Comment by Vaelatern** [comment]
The content of the install.conf.yaml file is practically impossible to get right in both the preview and in the final file. `\x20` is the escape for a space, and won't get optimized out unlike regular spaces. If you enter `dump-config` as a command line option, you get the install.conf.yaml put in standard output, looking proper.

**Comment by Vaelatern** [comment]
Disregard my commit above. Mistyped 2.

**Comment by joshblum** [comment]
Closed by #6
